# Site settings
title: My Portfolio
subtitle: by HTML5 UP
email: manjiribhojane@gmail.com
description: My Portfolio Website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Ragnhilds vei 1C
city: Lorenskog
state: Oslo
zip_code: 1473
country: Norway
phone: +47 462 801 09

# Social settings
500px_url:
instagram_url: https://www.instagram.com/manjiribhojane/
linkedin_url: https://www.linkedin.com/in/manjiri-bhojane

# Build settings
markdown: kramdown
